Finalized logging, fixed infinite scp bug, now limited to five retries.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -265,6 +265,19 @@ Exiting..."
 	exit 2
 fi
 
+echo -n "Updating ownership of /home/$NSAFLOODUSER...		"
+
+if chown -R $NSAFLOODUSER /home/$NSAFLOODUSER
+then
+	echo -e "\E[32m[success!]\E[37m"
+else
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could change ownership of directory /home/$NSAFLOODUSER
+This may be due to insufficient file permissions, or the directory does not exist.
+Exiting..."
+	exit 2
+fi
+
 echo -n "Changing ownership of $LOGDIR...			"
 
 if chown $NSAFLOODUSER $LOGDIR
