Change if statement syntax of install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -9,6 +9,10 @@ FILEMAN="nsaflood.1.gz"
 FILEMANSRC="nsaflood.1"
 FILESCHEDMAN="nsaf-sched.1.gz"
 FILESCHEDMANSRC="nsaf-sched.1"
+CONFIGDIR="/etc/nsaflood"
+CONFIGFILE="nsaflood.conf"
+CONFIGPEERTAB="peertab"
+LOGDIR="/var/log/nsaflood"
 
 if [ $UID != 0 ]; then
 
@@ -20,11 +24,11 @@ fi
 
 echo -n "Moving $FILEBIN to $DESTINATIONBIN...				"
 
-cp $CURRENTDIR/$FILEBIN $DESTINATIONBIN
-
-if [ $? -ne 0 ]; then
-
-	echo -e "\E[31mFAILURE!\E37m
+if cp $CURRENTDIR/$FILEBIN $DESTINATIONBIN
+then
+	echo -e "\E[32m[success!]\E[37m"
+else
+	echo -e "\E[31m[FAILURE!]\E[37m
 ERROR: Could not copy $FILEBIN to $DESTINATIONBIN
 This may be due to insufficient file permissions, or the partition being full.
 Exiting..."
@@ -32,77 +36,168 @@ Exiting..."
 	exit 2
 fi
 
-echo -ne "\E[32m[success!]\E[37m
-Updating file ownership and permissions on $FILEBIN...		"
+echo -n "Updating file ownership and permissions on $FILEBIN...		"
 
-chown 0:0 $DESTINATIONBIN/$FILEBIN
-chmod 755 $DESTINATIONBIN/$FILEBIN
+if ! chown 0:0 $DESTINATIONBIN/$FILEBIN
+then
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could not change ownership of $FILEMAN
+The file might not exist
+Exiting..."
+	exit 2
+fi
 
-echo -ne "\E[32m[success!]\E[37m
-Moving $FILESCHED to $DESTINATIONBIN...				"
+if chmod 755 $DESTINATIONBIN/$FILEBIN
+then
+	echo -e "\E[32m[success!]\E[37m"
+else
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could not change permissions of $FILEMAN
+The file might not exist
+Exiting..."
+	exit 2
+fi
 
-cp $CURRENTDIR/$FILESCHED $DESTINATIONBIN
+echo -n "Moving $FILESCHED to $DESTINATIONBIN...				"
 
-if [ $? -ne 0 ]; then
-
-	echo "\E[31mFAILURE!\E37m
+if cp $CURRENTDIR/$FILESCHED $DESTINATIONBIN
+then
+	echo -e "\E[32m[success!]\E[37m"
+else
+	echo -e "\E[31m[FAILURE!]\E[37m
 ERROR: Could not copy $FILESCHED to $DESTINATOINBIN
 This may be due to insufficent file permissions, or the partition being full.
 Exiting..."
-
 	exit 2
 fi
 
-echo -ne "\E[32m[success!]\E[37m
-Updating file ownership and permissions on $FILESCHED...	"
+echo -n "Updating file ownership and permissions on $FILESCHED...	"
 
-chown 0:0 $DESTINATIONBIN/$FILESCHED
-chmod 755 $DESTINATIONBIN/$FILESCHED
+if ! chown 0:0 $DESTINATIONBIN/$FILESCHED
+then
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could not change ownership of $FILEMAN
+The file might not exist
+Exiting..."
+	exit 2
+fi
+if chmod 755 $DESTINATIONBIN/$FILESCHED
+then
+	echo -e "\E[32m[success!]\E[37m"
+else
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could not change permissions of $FILEMAN
+The file might not exist
+Exiting..."
+	exit 2
+fi
 
-echo -ne "\E[32m[success!]\E[37m
-Compressing $FILEMANSRC and moving to $DESTINATIONMAN...	"
+echo -n "Compressing $FILEMANSRC and moving to $DESTINATIONMAN...	"
 
-gzip --stdout $CURRENTDIR/$FILEMANSRC > $DESTINATIONMAN/$FILEMAN
-
-if [ $? -ne 0 ]; then
-
-	echo "\E[31mFAILURE!\E37m
+if gzip --stdout $CURRENTDIR/$FILEMANSRC > $DESTINATIONMAN/$FILEMAN
+then
+	echo -e "\E[32m[success!]\E[37m"
+else
+	echo -e "\E[31m[FAILURE!]\E[37m
 ERROR: Could not copy $FILEMAN to $DESTINATIONMAN
 This may be due to insuffiencet file permissions, or the partition being full.
 Exiting..."
-
 	exit 2
 fi
 
-echo -ne "\E[32m[success!]\E[37m
-Updating file ownership and permissions of $FILEMAN...	"
+echo -n "Updating file ownership and permissions of $FILEMAN...	"
 
-chown 0:0 $DESTINATIONMAN/$FILEMAN
-chmod 744 $DESTINATIONMAN/$FILEMAN
+if ! chown 0:0 $DESTINATIONMAN/$FILEMAN
+then
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could not change ownership of $FILEMAN
+The file might not exist
+Exiting..."
+	exit 2
+fi
 
-echo -ne "\E[32m[success!]\E[37m
-Compressing $FILESCHEDMANSRC and moving to $DESTINATIONMAN...	"
+if chmod 744 $DESTINATIONMAN/$FILEMAN
+then
+	echo -e "\E[32m[success!]\E[37m"
+else
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could not change permissions of $FILEMAN
+The file might not exist
+Exiting..."
+	exit 2
+fi
+
+echo -n "Compressing $FILESCHEDMANSRC and moving to $DESTINATIONMAN...	"
 
 
-gzip --stdout $CURRENTDIR/$FILESCHEDMANSRC > $DESTINATIONMAN/$FILESCHEDMAN
-
-if [ $? -ne 0 ]; then
-
-	echo "\E[31mFAILURE!\E37m
+if gzip --stdout $CURRENTDIR/$FILESCHEDMANSRC > $DESTINATIONMAN/$FILESCHEDMAN
+then
+	echo -e "\E[32m[success!]\E[37m"
+else
+	echo -e "\E[31m[FAILURE!]\E[37m
 ERROR: Could not copy $FILESCHEDMAN to $DESTINATIONMAN
 This may be due to insufficient file permissions, or the partition being full.
 Exiting..."
-
 	exit 2
 fi
 
-echo -ne "\E[32m[success!]\E[37m
-Updating file ownership and permissions of $FILESCHEDMAN...	"
+echo -n "Updating file ownership and permissions of $FILESCHEDMAN...	"
 
-chown 0:0 $DESTINATIONMAN/$FILESCHEDMAN
-chmod 744 $DESTINATIONMAN/$FILESCHEDMAN
+if ! chown 0:0 $DESTINATIONMAN/$FILESCHEDMAN
+then
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could not change ownership of $FILEMANSCHED
+The file might not exist
+Exiting..."
+	exit 2
+fi
 
-echo -e "\E[32m[success!]\E[37m
-Installation of NSAFlood finished successfully."
+if chmod 744 $DESTINATIONMAN/$FILESCHEDMAN
+then
+	echo -e "\E[32m[success!]\E[37m"
+else
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could not change permissions of $FILEMANSCHED
+The file might not exist
+Exiting..."
+	exit 2
+fi
+
+echo -n "Creating $CONFIGDIR...					"
+
+if mkdir $CONFIGDIR > /dev/null 2>&1
+then
+	echo -e "\E[32m[success!]\E[37m"
+else
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could not create directory $CONFIGDIR
+This may be due to insufficient file permissions, or the directory exists.
+Exiting..."
+	exit 2
+fi
+
+echo -n "Creating configuration files...					"
+
+if ! cp $CONFIGFILE $CONFIGDIR/$CONFIGFILE
+then
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could not create file $CONFIGFILE
+This may be due to insufficient file permissions.
+Exiting..."
+	exit 2
+fi
+
+if touch $CONFIGDIR/$CONFIGPEERTAB
+then
+	echo -e "\E[32m[success!]\E[37m"
+else
+	echo -e "\E[31m[FAILURE!]\E[37m
+ERROR: Could not create file $CONFIGFILE
+This may be due to insufficient file permissions.
+Exiting..."
+	exit 2
+fi
+
+echo "Installation of NSAFlood finished successfully."
 
 exit 0
